### ISSUE TITLE
Set translation_domain for whole menu

### ISSUE THREAD

**Issue by exchentrix** [KnpLabs/KnpMenuBundle#328]
Hey,

is it possible to set the _translation_domain_ to the whole menu instead of specifying it on each menu node separately? 

`$root->setExtra('translation_domain', 'menu');`

doesn't work unfortunately.

Best,
Christian

**Comment by jonny827** [comment]
Hello @exchentrix  : 

I started running into my own KnpMenu Bundle's translation domain headaches due to the default folder Structure KnpMenuBundle expects the translation to be in and I ran into a post that may assist you in solving your headaches.   The solution was found in Issue #170 and was suggested by @nicodmf . 
[KnpMenuBundle I18n for your menu labels - translate all menus or only certain menus using specific translations domains](https://github.com/KnpLabs/KnpMenuBundle/blob/8cf6329e63e4bb8a14336c6facaa8d5f48f80f52/Resources/doc/i18n.rst)

For this suggested solution it extends the KNPMenu Twig Template and then you can pass the menu parameters for either for all menus or just for a certain menu.  I hope this helps you in your quest. 

If I have answered your question, please feel free to close the thread. I wish you the best of luck on your project(s)!

Warmest Regards,

Jonny827

**Comment by exchentrix** [comment]
Hey Jonny,

thank you very much for the advices. :)

**Comment by jonny827** [comment]
@exchentrix Anytime! I am glad I could help someone else. That is the beauty of a community, we support each other through the headaches. Also thank @nicodmf for the original answer. I just happened to stumble upon it when I remembered your query as I search KNPMenuBundle for anything related to translations in the issue area.  Best of luck to you on the rest of your projects!  Thank you for your gratitude and for closing the issue AND FOR THE EMOJI'S!!! You ROCK!!!
