### ISSUE TITLE
VoterInitializerListener is deprecated

### ISSUE THREAD

**Issue by ossinkine** [KnpLabs/KnpMenuBundle#367]
When app is started first time and container is compiled, the error `The Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener class is deprecated since 2.2 and will be removed in 3.0` is triggered.

**Comment by stof** [comment]
Is it the only deprecation warning your are seeing ? Or are you also seeing a deprecation about `Using the "request" attribute of the "knp_menu.voter" tag is deprecated since version 2.2. Inject the RequestStack in the voter instead.` ?

If you see this other deprecation, fixing it will lead to not using the VoterInitializerListener anymore.

If there is no such deprecation, it would mean that we fail at removing the usage of the listener properly when it is useless.

**Comment by ossinkine** [comment]
I see only this message.
I've just updated to 2.2.0 version.

**Comment by mmucklo** [comment]
It seems the problem is with the knp_menu.listener.voters service which is still tagged in menu.xml

**Comment by ossinkine** [comment]
All correct, listener is removed in [AddVotersPass.php#L50](https://github.com/KnpLabs/KnpMenuBundle/blob/master/src/DependencyInjection/Compiler/AddVotersPass.php#L50) if voters don't use `request` tag attribute. So you should avoid using `request` tag attribute and you won't see deprecation notification.
